server.port = 8000

# Azure SQL 連接設定
spring.datasource.url=jdbc:sqlserver://petlove.database.windows.net:1433;database=PetDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=petapp_admin
spring.datasource.password=groupH115
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 讓 Spring Boot 自動幫你對應實體類 (Optional)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG