INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'汪貓星球', N'慢烘鮮食蔬肉糧(鮮蔬嫩雞餐)', N'挑食、腸胃或皮膚敏感', N'全年齡', N'全適用', N'狗', 0, 1, 430);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'汪貓星球', N'慢烘鮮食蔬肉糧(鮮蔬牛魚餐)', N'挑食、腸胃或皮膚敏感', N'全年齡', N'全適用', N'狗', 0, 1, 414);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'汪貓星球', N'脫水生肉糧 小方粒型(安心雞)', N'敏感、挑食、體重管理', N'全年齡', N'全適用', N'貓', 1, 1, 453);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'汪貓星球', N'脫水生肉糧 小方粒型(低敏鴨)', N'敏感、挑食、體重管理', N'全年齡', N'全適用', N'貓', 1, 1, 480);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'汪貓星球', N'脫水生肉糧 小方粒型(營養鱈魚)', N'敏感、挑食、體重管理', N'幼貓', N'全適用', N'貓', 1, 1, 466);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 小型犬配方(雞肉)', N'消化系統不好、皮毛不健康', N'成犬', N'小型犬', N'狗', 0, 1, 417);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 小型犬配方(牛肉)', N'消化系統不好、皮毛不健康', N'成犬', N'小型犬', N'狗', 0, 1, 428.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 純凍乾配方(雞肉)', N'皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 1, 470.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 全犬配方(雞肉)', N'消化系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 1, 316);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 全犬配方(羊肉)', N'消化系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 1, 373);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 全犬配方(鮭魚+牛肉)', N'消化系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 1, 377.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 全犬配方(牛肉)', N'消化系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 1, 377);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 胖犬配方(雞肉)', N'腸胃不好、體重過胖、想維持體態', N'成犬', N'胖犬', N'狗', 0, 1, 359);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列 全犬配方(雞肉)', N'腸胃不好', N'全年齡', N'全適用', N'狗', 0, 1, 411);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'低敏系列 成犬配方(羊肉)', N'腸胃不好、皮毛不健康、過敏原多、免疫系統不好', N'成犬', N'全適用', N'狗', 0, 1, 431.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'低敏系列 成犬配方(鮭魚)', N'腸胃不好、皮毛不健康、過敏原多、免疫系統不好', N'成犬', N'全適用', N'狗', 0, 1, 433.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'無穀系列 全犬配方(鮭魚)', N'消化系統不好、牙口不好', N'全年齡', N'全適用', N'狗', 0, 1, 457);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'無穀系列 全犬配方(牛肉)', N'消化系統不好、牙口不好', N'全年齡', N'全適用', N'狗', 0, 1, 436);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'天然糙米 全犬配方(鮭魚)', N'消化系統不好、牙口不好', N'成犬', N'全適用', N'狗', 0, 1, 359.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'天然糙米 全犬配方(雞肉)', N'消化系統不好、牙口不好', N'成犬', N'全適用', N'狗', 0, 1, 358.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'天然燕麥 全犬配方(羊肉)', N'消化系統不好、牙口不好', N'成犬', N'全適用', N'狗', 0, 1, 371);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'天然大麥 全犬配方(牛肉)', N'消化系統不好、皮毛不健康', N'成犬', N'全適用', N'狗', 0, 1, 375.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列  全貓配方(雞肉)', N'消化系統不好、皮毛不健康', N'全年齡', N'全適用', N'貓', 0, 1, 432);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'凍乾系列  成貓配方(低脂雞肉)', N'腸胃不好、體重過胖、想維持體態', N'成貓', N'胖貓', N'貓', 0, 1, 370.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'無穀系列  全貓配方(雞肉)', N'消化系統不好、牙口不好', N'全年齡', N'全適用', N'貓', 0, 1, 430);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'無穀系列  成貓配方(雞肉)', N'消化系統不好、牙口不好', N'成貓', N'全適用', N'貓', 0, 1, 430);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'無穀系列  幼貓配方(雞肉)', N'消化系統不好、牙口不好', N'幼貓', N'全適用', N'貓', 0, 1, 445.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'無穀系列  成貓配方(鮭魚)', N'消化系統不好、牙口不好', N'成貓', N'全適用', N'貓', 0, 1, 447);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'皇極系列  成貓配方(雞肉)', N'皮毛不健康，抵抗力不好', N'成貓', N'全適用', N'貓', 0, 1, 447);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'原點', N'低敏系列  成貓配方(鮭魚)', N'皮毛不健康，腸胃不好', N'成貓', N'全適用', N'貓', 0, 1, 440);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'沛多富', N'羊肉加糙米', N'消化系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 0, 330);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'沛多富', N'雞肉加糙米', N'消化系統不好、肌肉發育', N'全年齡', N'全適用', N'狗', 0, 0, 323);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'小型成犬11種肉無榖狗飼料(雞肉+魚肉+蔬果)', N'消化系統不好、眼睛保健', N'全年齡', N'小型犬', N'狗', 1, 1, 390);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞高齡犬無榖狗飼料(雞肉+魚肉+蔬果)', N'消化系統不好、體重管理、維持肌肉量', N'高齡犬', N'全適用', N'狗', 1, 1, 371);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞室內犬無榖狗飼料(雞肉+魚肉+蔬果)', N'消化系統不好、想維持體態', N'全年齡', N'全適用', N'狗', 1, 1, 353);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'六種鮮魚犬無榖狗飼料(魚肉+蔬果)', N'消化系統不好', N'全年齡', N'全適用', N'狗', 1, 1, 388);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞成犬無榖狗飼料(雞肉+魚肉+蔬果)', N'消化系統不好', N'成犬', N'全適用', N'狗', 1, 1, 386);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞無榖幼犬飼料(雞肉+魚肉+蔬果)', N'消化系統不好', N'幼犬', N'全適用', N'狗', 1, 1, 400);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'海洋魚小型犬無榖狗飼料(魚肉+蔬果)', N'消化系統不好、肌肉發育、皮毛不健康', N'全年齡', N'小型犬', N'狗', 1, 1, 371);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞小型幼犬無榖狗飼料(雞肉+魚肉+蔬果)', N'消化系統不好、肌肉發育、皮毛不健康', N'全年齡', N'小型犬', N'狗', 1, 1, 400);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞愛貓無榖貓飼料(雞肉+魚肉+蔬果)', N'消化系統不好、皮毛不健康、心臟不好', N'全年齡', N'全適用', N'貓', 1, 1, 416);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞室內貓無榖貓飼料(雞肉+魚肉+蔬果)', N'消化系統不好、體重管理、皮毛不健康', N'全年齡', N'全適用', N'貓', 1, 1, 371);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'六種鮮魚無榖貓飼料(魚肉+蔬果)', N'消化系統不好、皮毛不健康、心臟不好', N'全年齡', N'全適用', N'貓', 1, 1, 407);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'愛貓守護8無榖貓飼料(雞肉+魚肉+蔬果)', N'腸胃不好、皮毛不健康、免疫系統不好、維持肌肉量、
關節不好、眼睛保健、心血管保健、腦部發育', N'全年齡', N'全適用', N'貓', 1, 1, 398);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'歐睿健', N'鮮雞無榖幼貓飼料(雞肉+魚肉+蔬果)', N'消化系統不好、腦部發育、肌肉發育', N'幼貓', N'全適用', N'貓', 1, 1, 412);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'山野雞無穀貓香草糧(雞肉+蔬果)', N'消化系統不好、泌尿保健、免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'貓', 0, 0, 364);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'國王鮭無穀貓香草糧(魚肉+蔬果)', N'心血管保健、皮毛不健康、免疫系統不好、
泌尿保健、消化系統不好', N'全年齡', N'全適用', N'貓', 0, 0, 364);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'放牧羊無穀貓香草糧(羊肉+蔬果)', N'消化系統不好、泌尿保健、免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'貓', 0, 0, 364);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'草原牛無穀貓香草糧(牛肉+蔬果)', N'消化系統不好、泌尿保健、免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'貓', 0, 0, 364);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'山野雞無穀犬香草糧(雞肉+蔬果)', N'消化系統不好、泌尿保健、免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 0, 330);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'國王鮭無穀犬香草糧(魚肉+蔬果)', N'骨骼保健、消化系統不好、泌尿保健、
免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 0, 330);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'放牧羊無穀犬香草糧(羊肉+蔬果)', N'消化系統不好、泌尿保健、免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 0, 330);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'香草廚坊', N'草原牛無穀犬香草糧(牛肉+蔬果)', N'消化系統不好、泌尿保健、免疫系統不好、皮毛不健康', N'全年齡', N'全適用', N'狗', 0, 0, 330);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'K36 幼貓專用乾糧', N'免疫力不好、腸胃不好、幫助大腦發育', N'幼貓', N'全適用', N'貓', 1, 1, 385.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'F32 理想體態成貓專用乾糧', N'泌尿道不好、想維持理想體態、化毛不順利、腸道不健康', N'成貓', N'全適用', N'貓', 1, 1, 383.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'E33 挑嘴貓濃郁香味配方', N'挑食、想要毛髮亮麗、維持理想體重', N'成貓', N'全適用', N'貓', 0, 0, 364.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'S37 絕育貓專用乾糧', N'想維持理想體重、泌尿系統不好、想維持肌肉量', N'成貓', N'全適用', N'貓', 1, 1, 362.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'L40 體重控制成貓專用乾糧', N'想維持理想體重、需要減肥、想維持肌肉量', N'成貓', N'全適用', N'貓', 1, 1, 338.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'IN27 室內成貓專用乾糧', N'泌尿系統不好、化毛不順利、減少熱量、糞便狀態不理想', N'成貓', N'全適用', N'貓', 1, 1, 374.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BSK38 英國短毛幼貓專用乾糧', N'增強免疫力、消化不好、幫助肌肉及骨骼發育', N'幼貓', N'全適用', N'貓', 1, 1, 418.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'S33 腸胃敏感成貓專用乾糧', N'消化道不好、有軟便現象、腸胃不好、進食少', N'成貓', N'全適用', N'貓', 1, 1, 428.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'IH34 加強化毛成貓專用乾糧', N'化毛不順利、想要毛髮亮麗、有牙垢', N'成貓', N'全適用', N'貓', 1, 1, 376.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'E35 絕佳口感成貓專用乾糧', N'挑食、維持理想體重、維持泌尿道健康', N'成貓', N'全適用', N'貓', 1, 1, 394.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'UC33 泌尿保健成貓專用乾糧', N'泌尿道不好', N'成貓', N'全適用', N'貓', 0, 0, 339.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'O30 強效潔牙成貓專用乾糧', N'嘴巴臭、有牙垢', N'成貓', N'全適用', N'貓', 1, 1, 371.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'HS33 亮毛護膚成貓專用乾糧', N'化毛不順利、想要毛髮亮麗、皮膚不好', N'成貓', N'全適用', N'貓', 0, 0, 383.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'RD32 布偶成貓專用乾糧', N'維持骨骼健康、心臟保健、維持泌尿道健康', N'成貓', N'全適用', N'貓', 1, 1, 398.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'E35 挑嘴貓絕佳口感成貓專用乾糧', N'維持理想體重、想要毛髮亮麗、挑食', N'成貓', N'全適用', N'貓', 0, 0, 374.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'IN+7 室內老貓專用乾糧', N'維持腎臟健康、泌尿系統不好、降低糞便異味', N'老貓', N'全適用', N'貓', 0, 0, 359);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BS34 英國短毛成貓專用乾糧', N'關節保健、心臟保健、維持泌尿系統健康', N'成貓', N'全適用', N'貓', 1, 1, 400.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'E42  挑嘴貓營養滿分配方', N'挑食、維持理想體重、維持泌尿道健康', N'成貓', N'全適用', N'貓', 0, 0, 364.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'S36+7 絕育熟齡貓 (7歲以上)專用乾糧', N'降低絕育後肥胖機率、活力低、維持腎臟健康、維持泌尿道健康', N'成貓', N'全適用', N'貓', 1, 1, 368.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BC34 離乳貓與母貓專用乾糧', N'哺乳期母貓、保健幼貓免疫系統、幫助幼貓大腦發育', N'幼貓', N'全適用', N'貓', 1, 1, 442.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BG40 豹成貓專用乾糧', N'腸胃敏感、想要毛髮亮麗、支援活力和彈跳力', N'成貓', N'全適用', N'貓', 1, 1, 403.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'P30 波斯貓 (長毛貓、金吉拉) 專用乾糧', N'消化不好、化毛不順利、想要毛髮亮麗', N'成貓', N'全適用', N'貓', 1, 1, 413.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'A30+11 老貓11歲以上專用飼料', N'沒活力、體重變輕、牙口不好、皮膚毛髮變差', N'老貓', N'全適用', N'貓', 1, 1, 403.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'A30+15 老貓15歲以上專用飼料', N'沒活力、體重變輕、牙口不好、皮膚毛髮變差、大腦老化', N'老貓', N'全適用', N'貓', 1, 1, 422.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'S30+11 絕育老貓11歲以上專用飼料', N'沒活力、體重變輕、牙口不好、皮膚毛髮變差、腎臟不好', N'老貓', N'全適用', N'貓', 1, 1, 374.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'E42 挑嘴成貓營養滿分飼料 ', N'維持理想體重、挑食、泌尿系統不好', N'成貓', N'全適用', N'貓', 1, 1, 390.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'M25/MA 中型成犬專用乾糧', N'消化不好、挑食、免疫力不好、想維持理想體重', N'成犬', N'中型犬', N'狗', 1, 1, 384.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'PR27/MNA 小型成犬專用乾糧', N'有牙結石、挑食、想維護亮麗毛髮、想維持理想體重', N'成犬', N'小型犬', N'狗', 0, 0, 360);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'S26 柴犬成犬專用乾糧', N'皮毛不健康、消化系統不健康、有牙垢、想維持體態', N'成犬', N'中、小型犬', N'狗', 1, 1, 376.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BHN/PA 博美成犬專用乾糧', N'關節不好、皮毛不健康、腸胃不健康', N'成犬', N'小型犬', N'狗', 1, 1, 394.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'APR33/MNP 小型幼犬專用乾糧', N'維持免疫力、消化不好，食慾不好', N'幼犬', N'小型犬', N'狗', 1, 1, 406.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'AGR32/MXP 大型幼犬專用乾糧', N'維持免疫力、保護關節，幫助發育、幫助消化', N'幼犬', N'大型犬', N'狗', 1, 1, 380.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'AM32/MP 中型幼犬專用乾糧', N'維持免疫力、幫助大腦發育、保護腸道', N'幼犬', N'中型犬', N'狗', 1, 1, 413.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'CHA/BHN 吉娃娃幼犬專用乾糧', N'維持免疫力、降低排便量及異味', N'幼犬', N'小型犬', N'狗', 1, 1, 405.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MNINP 小型室內幼犬專用乾糧', N'維持免疫力、降低排便量及異味、幫助大腦發育', N'幼犬', N'小型犬', N'狗', 1, 1, 395.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'RPJ33/PDP 貴賓幼犬專用乾糧', N'維持免疫力、想維護亮麗毛髮、維持腸道健康', N'幼犬', N'小型犬', N'狗', 1, 1, 404);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MNINA 小型室內成犬專用乾糧', N'腸胃蠕動慢、容易胖、皮膚不好、糞便味道大', N'成犬', N'小型犬', N'狗', 1, 1, 395.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'DMMN 皮膚保健小型成犬專用乾糧', N'皮膚不健康', N'成犬', N'小型犬', N'狗', 0, 0, 376.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'PDA/PRP30 貴賓成犬專用乾糧', N'想維護亮麗毛髮、想維持理想體重、有牙垢', N'成犬', N'小型犬', N'狗', 1, 1, 407);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'DGMN 腸胃保健小型成犬專用乾糧', N'消化系統不好、想要平衡腸道菌叢', N'成犬', N'小型犬', N'狗', 0, 0, 397.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'LWMN 體重控制小型成犬專用乾糧', N'需要體重管理、維持骨骼關節健康', N'成犬', N'小型犬、胖犬', N'狗', 1, 1, 323.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'UMN 泌尿保健小型成犬專用乾糧', N'泌尿系統不健康、喝水量少', N'成犬', N'小型犬', N'狗', 1, 1, 382.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MXA 大型成犬專用乾糧', N'消化不好、關節不好、維持皮膚健康', N'成犬', N'大型犬', N'狗', 1, 1, 397.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'SHN 小型離乳犬與母犬專用乾糧', N'維持幼犬消化道安全性與免疫力、母犬所需營養', N'幼犬', N'小型犬', N'狗', 1, 1, 420.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MNINA+8 小型室內熟齡犬專用乾糧', N'牙齦不健康、沒活力、降低糞便異味', N'老犬', N'小型犬', N'狗', 1, 1, 382.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MNA+8 小型熟齡犬專用乾糧', N'維持理想體重、皮膚不健康', N'老犬', N'小型犬', N'狗', 0, 0, 397.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MNA+12 小型老犬12+歲專用乾糧', N'維持理想體重、骨骼關節不好、沒活力', N'老犬', N'小型犬', N'狗', 1, 1, 385.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'XSA+8 迷你型熟齡犬專用乾糧', N'維持泌尿道健康、沒活力、維護腸道健康、皮膚不健康', N'老狗', N'迷你犬', N'狗', 1, 1, 400.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'XSA+12  迷你型老犬12+歲專用乾糧', N'腸胃不好、腎臟不好、維護牙齒健康、沒活力、心臟不好', N'老狗', N'迷你型', N'狗', 1, 1, 395.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'M+7 中型成熟犬專用乾糧', N'腸道不健康、想維護亮麗毛髮、有牙結石', N'成犬', N'中型犬', N'狗', 1, 1, 385.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'STA 西施成犬專用乾糧', N'有牙垢、想維護亮麗毛髮、降低糞便異味', N'成犬', N'小型犬', N'狗', 1, 1, 399.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'CHA 吉娃娃成犬專用乾糧', N'消化不好、口腔不好、糞便異味重', N'成犬', N'小型犬', N'狗', 1, 1, 392.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'XSA 迷你型成犬專用乾糧', N'腸道不健康、想維護亮麗毛髮、牙齒不好、泌尿道不健康', N'成犬', N'迷你犬', N'狗', 1, 1, 400.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'SNA 迷你雪納犬成犬專用乾糧', N'皮膚敏感、泌尿問題、食慾太旺盛', N'成犬', N'小型犬', N'狗', 1, 1, 362.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'YSA 約克夏成犬專用乾糧', N'有牙垢、想維護亮麗毛髮、挑食、沒活力', N'成犬', N'迷你犬', N'狗', 1, 1, 394.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'DSA/PRD28 臘腸成犬專用乾糧', N'關節不好、維持理想體重、糞便異味重', N'成犬', N'小型犬', N'狗', 1, 1, 372.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'DSP 臘腸幼犬專用乾糧', N'幫助關節發育、維護免疫力、維持腸道健康', N'幼犬', N'小型犬', N'狗', 1, 1, 388.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BDA 鬥牛成犬專用乾糧', N'腸胃敏感、有異位性皮膚炎、容易脹氣', N'成犬', N'小型犬', N'狗', 1, 1, 403.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'FBDP 法國鬥牛幼犬專用乾糧', N'維持腸道健康、皮膚屏障受損、抵抗力不好', N'幼犬', N'小型犬', N'狗', 0, 0, 414);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'FBDA 法國鬥牛成犬專用乾糧', N'糞便異味重、維持肌肉、皮膚屏障受損', N'成犬', N'小型犬', N'狗', 1, 1, 403.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'M+10 中型老犬專用乾糧', N'維護免疫力、肌肉量不足、沒活力', N'老犬', N'中型犬', N'狗', 1, 1, 386.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'DMMX 皮膚保健大型成犬專用乾糧', N'皮膚不好、狀況不佳、毛髮不好', N'成犬', N'大型犬', N'狗', 1, 1, 396.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'PUGA 巴哥成犬專用乾糧', N'維持健美體態、皮膚屏障受損', N'成犬', N'小型犬', N'狗', 0, 0, 389.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MTA 馬爾濟斯成犬專用乾糧', N'毛髮不好、糞便氣味重、咬合力弱、挑食', N'成犬', N'迷你型', N'狗', 1, 1, 405.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MXA+5 大型熟齡犬專用乾糧', N'沒活力、關節不好、吸收力不好', N'成犬', N'大型犬', N'狗', 1, 1, 389.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MXA+8 大型老齡犬8歲以上專用飼料', N'免疫系統減弱、關節退化、消化道功能差', N'老犬', N'大型犬', N'狗', 1, 1, 388.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'DMM 皮膚保健中型成犬專用乾糧', N'皮膚不好、狀況不佳、毛髮不好', N'成犬', N'中型犬', N'狗', 1, 1, 398.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'BCA 比熊成犬專用飼料', N'泌尿道不健康、維持理想體態、想要維護毛髮', N'成犬', N'小型犬', N'狗', 1, 1, 386.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'GRA 黃金獵犬成犬專用飼料', N'皮膚敏感、心臟不好、維持理想體重', N'成犬', N'大型犬', N'狗', 1, 1, 361.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'法國皇家', N'MNS 小型離乳犬與母犬專用飼料', N'能量需求高、免疫保護力下降、消化不好', N'幼犬', N'小型犬', N'狗', 1, 1, 420.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'大型幼犬 草本活力犬糧(雞肉+番茄乾+枸杞)', N'需要均衡發育、沒活力、抵抗力不好', N'幼犬', N'大型犬', N'狗', 0, 1, 395.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'全齡犬 草本美毛犬糧(雞肉鮭魚+百合根)', N'皮膚不好、沒活力、想維護亮麗毛髮', N'全年齡', N'全適用', N'狗', 0, 1, 388.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'大型成犬 草本活力犬糧(火雞肉+胡蘿蔔+枸杞)', N'腸胃不健康、骨質保健、想維護亮麗毛髮', N'成犬', N'大型犬', N'狗', 0, 1, 387.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'中小型幼犬 草本犬糧(雞肉+豌豆+黨參)', N'維持抵抗力、維持腸道健康', N'幼犬', N'中、小型犬', N'狗', 0, 1, 386.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'中小型成犬 草本犬糧(火雞肉+豌豆+黨參) ', N'維持抵抗力、沒活力、想維護亮麗毛髮', N'成犬', N'中、小型犬', N'狗', 0, 1, 386.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'高齡犬 草本犬糧(火雞肉+豌豆+黃耆)', N'維護抵抗力、維持腸道健康、骨質保健', N'老犬', N'全適用', N'狗', 0, 1, 378.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'全齡貓 草本美毛貓糧(雞肉鮭魚+百合根)', N'皮膚不好、沒活力、想維護亮麗毛髮', N'全年齡', N'全適用', N'貓', 0, 1, 385.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'成貓 草本貓糧(雞肉+胡蘿蔔+黨參)', N'化毛不順利、想要毛髮亮麗、維持泌尿道健康', N'成貓', N'全適用', N'貓', 0, 1, 385.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'絕育成貓 草本貓糧(火雞肉+豌豆+茯苓)', N'維持理想體重、腸胃不健康、維持泌尿道健康', N'成貓', N'全適用', N'貓', 0, 1, 371.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'自然主義', N'幼貓 草本貓糧(雞肉+豌豆+黨參)', N'維護抵抗力、維持腸道健康', N'幼貓', N'全適用', N'貓', 0, 1, 389.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'幼犬去骨雞肉無穀配方', N'維護免疫力、營養不良', N'幼犬', N'全適用', N'狗', 1, 1, 374.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'成犬去骨雞肉無穀配方', N'維護免疫力、營養不良、保護關節、排便不順', N'成犬', N'全適用', N'狗', 1, 1, 365.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'成犬鮭魚無穀配方', N'維護免疫力、營養不良、保護關節', N'成犬', N'全適用', N'狗', 1, 1, 365.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'成貓去骨雞肉無穀配方', N'維護免疫力、營養不良、保護關節、排便不順', N'成貓', N'全適用', N'貓', 1, 1, 374.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'成貓鮭魚無穀配方', N'維護免疫力、營養不良、保護關節', N'成貓', N'全適用', N'貓', 1, 1, 372.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'成貓鴨肉無穀配方 ', N'維護免疫力、營養不良、保護關節、軟便、有粉刺', N'成貓', N'全適用', N'貓', 1, 1, 369.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'藍摯', N'幼貓去骨雞肉無穀配方', N'維護免疫力、營養不良', N'幼貓', N'全適用', N'貓', 1, 1, 395.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 雞肉與大麥特調食譜', N'維持精實肌肉、想維持毛髮亮麗', N'成犬', N'全適用', N'狗', 1, 0, 367.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 羊肉與糙米特調食譜', N'維持精實肌肉、想維持毛髮亮麗', N'成犬', N'全適用', N'狗', 1, 0, 371.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 雞肉與大麥特調食譜(小顆粒)', N'促進肌肉精實、想維持毛髮亮麗、挑食', N'成犬', N'全適用', N'狗', 1, 0, 368.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'幼犬 雞肉與糙米特調食譜', N'幫助骨骼生長、支持腦部發育、維持腸道健康、維護免疫力、促進肌肉精實', N'幼犬', N'全適用', N'狗', 1, 0, 374.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'幼犬 雞肉與糙米特調食譜(小顆粒)', N'幫助骨骼生長、支持腦部發育、維持腸道健康、維護免疫力、促進肌肉精實、挑食', N'幼犬', N'全適用', N'狗', 1, 0, 374.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 羊肉與糙米特調食譜(小顆粒)', N'促進肌肉精實、挑食', N'成犬', N'全適用', N'狗', 1, 0, 372.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 腫瘤營養照護(處方食品)', N'食慾不好、沒活力、維持腸道健康、穩定糞便品質、癌症', N'全年齡', N'全適用', N'狗', 1, 0, 415.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 t/d (小顆粒)(處方食品)', N'有牙菌斑、牙漬和牙垢堆積、清理牙齦、口氣臭', N'成犬', N'小型犬', N'狗', 1, 0, 346.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 t/d (原顆粒)(處方食品)', N'有牙菌斑、牙漬和牙垢堆積、清理牙齦、口氣臭', N'成犬', N'全適用', N'狗', 1, 0, 346.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 完美消化', N'維持腸道健康、營養不良、維持精實肌肉、想要維持器官健康', N'成犬', N'全適用', N'狗', 1, 0, 366.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬7歲以上 完美消化(小顆粒)', N'維持腸道健康、營養不良、維持精實肌肉、想要維持器官健康', N'老犬', N'全適用', N'狗', 1, 0, 355.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 i/d (小顆粒)(處方食品)', N'消化不良、維護免疫力、挑食、排便不順', N'成犬', N'小型犬', N'狗', 1, 0, 358.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 i/d (原顆粒)(處方食品)', N'消化不良、維護免疫力、挑食、排便不順', N'成犬', N'全適用', N'狗', 1, 0, 358.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 7歲以上 高齡活力 雞肉特調食譜', N'沒活力、消化不好、想維持毛髮亮麗', N'老犬', N'全適用', N'狗', 1, 0, 361.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 完美體重 雞肉與糙米特調食譜', N'體重過胖', N'成犬', N'胖犬', N'狗', 1, 0, 318.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'幼犬 敏感胃腸與皮膚 鮭魚與糙米特調食譜', N'腸胃不好、想維持毛髮亮麗、皮膚不好、支持腦部發育', N'幼犬', N'全適用', N'狗', 1, 0, 385.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 k/d(處方食品)', N'腎臟不好、食慾不好、腸胃不好', N'成犬', N'全適用', N'狗', 1, 0, 399.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 i/d 低脂(處方食品)', N'消化不良、有泌尿道結石、想維持免疫系統健康、穩定糞便品質、有血脂', N'成犬', N'全適用', N'狗', 1, 0, 331.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 GI Biome 健康腸菌叢(小顆粒)(處方食品)', N'軟便、腸胃不好、消化不良', N'成犬', N'小型犬', N'狗', 1, 0, 332.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 GI Biome 健康腸菌叢(原顆粒)(處方食品)', N'軟便、腸胃不好、消化不良', N'成犬', N'全適用', N'狗', 1, 0, 332.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 11歲以上 雞肉、糙米與大麥特調食譜', N'維持心臟，腎臟及膀胱健康、關節不好、保持消化，免疫和器官健康', N'老犬', N'迷你、小型犬', N'狗', 1, 0, 380.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 完美消化', N'維持腸道健康、營養不良、維持精實肌肉、想要維持器官健康', N'成犬', N'迷你、小型犬', N'狗', 1, 0, 370.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 7歲以上 雞肉與糙米特調食譜', N'維持心臟，腎臟及膀胱健康、關節不好、保持消化，想維持理想體重', N'老犬', N'迷你、小型犬', N'狗', 1, 0, 361.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 雞肉與糙米特調食譜', N'支持消化，免疫和器官健康、消化不良、想維持理想體重、幫助肌肉精實', N'成犬', N'迷你、小型犬', N'狗', 1, 0, 369.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 完美體重 雞肉與糙米特調食譜', N'體重過胖', N'成犬', N'胖犬', N'狗', 1, 0, 318.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 敏感胃腸與皮膚', N'腸胃敏感、想維持毛髮亮麗、消化不良', N'成犬', N'迷你、小型犬', N'狗', 1, 0, 372.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 7歲以上 高齡活力 雞肉與米特調食譜', N'沒活力、想維持毛髮亮麗、維持腦部健康', N'老犬', N'迷你、小型犬', N'狗', 1, 0, 364.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 d/d 馬鈴薯及鴨肉(處方食品)', N'皮膚不好、食物敏感、穩定糞便狀態、加強免疫系統', N'成犬', N'全適用', N'狗', 1, 0, 365.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 d/d 馬鈴薯及鮭魚(處方食品)', N'皮膚不好、食物敏感、穩定糞便狀態、加強免疫系統', N'成犬', N'全適用', N'狗', 1, 0, 364.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 z/d (小顆粒)(處方食品)', N'食物敏感、腸胃不好、改善毛髮狀態、稀便、降低泌尿道結石', N'成犬', N'小型犬', N'狗', 1, 0, 350.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 z/d (原顆粒)(處方食品)', N'食物敏感、腸胃不好、改善毛髮狀態、稀便、降低泌尿道結石', N'成犬', N'全適用', N'狗', 1, 0, 350.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 u/d(處方食品)', N'想維持免疫系統健康、膀胱問題、頻尿、血尿、有膀胱結石', N'成犬', N'全適用', N'狗', 1, 0, 398.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 c/d 全效(處方食品)', N'泌尿道不健康、有膀胱結石、膀胱問題', N'成犬', N'全適用', N'狗', 1, 0, 382);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 Metabolic體重管理(處方食品)', N'體重過胖、食慾太好、降低泌尿道結石', N'成犬', N'全適用', N'狗', 1, 0, 312.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 h/d(處方食品)', N'保持心臟健康、血壓不正常、加強免疫系統、支持肝臟和腎臟功能', N'成犬', N'全適用', N'狗', 1, 0, 400.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 r/d(處方食品)', N'維持精實肌肉、加強免疫系統、體重過胖', N'成犬', N'胖犬', N'狗', 1, 0, 294.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 j/d (原顆粒)(處方食品)', N'關節不好、加強免疫系統、降低泌尿道結石、維持精實肌肉', N'成犬', N'全適用', N'狗', 1, 0, 367);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 Metabolic體重管理+j/d(處方食品)', N'體重過胖、關節不好', N'成犬', N'胖犬', N'狗', 1, 0, 322.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 w/d(處方食品)', N'體重過胖、血糖不正常、穩定糞便狀態、泌尿道不健康、想維持精實肌肉', N'成犬', N'胖犬', N'狗', 1, 0, 310);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'犬用 l/d(處方食品)', N'肝臟不健康、加強免疫系統', N'幼犬', N'全適用', N'狗', 1, 0, 399.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'大型幼犬 雞肉與糙米特調食譜', N'幫助骨骼生長、支持腦部發育、維持腸道健康、維護免疫力、促進肌肉精實', N'幼犬', N'大型犬', N'狗', 1, 0, 362.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'大型成犬 雞肉與大麥特調食譜', N'維持消化健康、保護關節、想維持免疫系統健康、想維持毛髮亮麗', N'成犬', N'大型犬', N'狗', 1, 0, 365.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 7歲以上 雞肉、大麥與糙米特調食譜(小顆粒)', N'想維持毛髮亮麗、沒活力', N'老犬', N'全適用', N'狗', 1, 0, 355);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 鮭魚與糙米特調食譜', N'想維持免疫系統健康、想維持毛髮亮麗、想維持精實肌肉', N'成犬', N'全適用', N'狗', 1, 0, 361.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 低卡 含雞肉與大麥(小顆粒)', N'想維持免疫系統健康、想維持毛髮亮麗、想維持精實肌肉、想維持理想體重', N'成犬', N'胖犬、小型犬', N'狗', 1, 0, 298.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 7歲以上 雞肉、大麥與米特調食譜', N'想維持毛髮亮麗、沒活力', N'老犬', N'全適用', N'狗', 1, 0, 355);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 低卡 含雞肉與大麥', N'想維持免疫系統健康、想維持毛髮亮麗、想維持精實肌肉、想維持理想體重', N'成犬', N'胖犬', N'狗', 1, 0, 298.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你幼犬 雞肉與糙米特調食譜', N'幫助骨骼生長、支持腦部發育、維持腸道健康、維護免疫力、促進肌肉精實', N'幼犬', N'迷你、小型犬', N'狗', 1, 0, 378);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成犬 敏感胃腸與皮膚 雞肉特調食譜', N'腸胃不好、皮膚不好、消化不好、想維持毛髮亮麗', N'成犬', N'全適用', N'狗', 1, 0, 373.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'小型及迷你成犬 口腔保健 雞肉、米與大麥特調食譜', N'有牙菌斑及牙垢、口氣臭、想維持毛髮亮麗', N'成犬', N'迷你、小型犬', N'狗', 1, 0, 347.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 腫瘤營養照護(處方食品)', N'食慾不好、沒活力、維持腸道健康、穩定糞便品質、癌症', N'成貓', N'全適用', N'貓', 1, 0, 418.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 t/d(處方食品)', N'有牙菌斑、牙漬和牙垢堆積、清理牙齦、口氣臭', N'成貓', N'全適用', N'貓', 1, 0, 352);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 c/d 全效 紓解緊迫(處方食品)', N'有膀胱結石、膀胱問題、泌尿道不健康、壓力大', N'成貓', N'全適用', N'貓', 1, 0, 384.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 GI Biome 健康腸菌叢 紓解緊迫(處方食品)', N'消化不良、壓力大、排便不順、腸胃不好', N'成貓', N'全適用', N'貓', 1, 0, 380.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 i/d(處方食品)', N'消化不良、維護免疫力、挑食、排便不順', N'成貓', N'全適用', N'貓', 1, 0, 393.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 c/d 全效+體重管理(處方食品)', N'體重過胖、泌尿道不健康、有膀胱結石', N'成貓', N'胖貓', N'貓', 1, 0, 325.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 完美消化 鮭魚、糙米及全燕麥特調食譜', N'維持腸道健康、營養不良、維持精實肌肉、想要維持器官健康', N'成貓', N'全適用', N'貓', 1, 0, 384.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用k/d 雞肉(處方食品)', N'腎臟不好、食慾不好、腸胃不好', N'成貓', N'全適用', N'貓', 1, 0, 408.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 口腔保健 雞肉與糙米特調食譜', N'有牙菌斑及牙垢、口氣臭', N'成貓', N'全適用', N'貓', 1, 0, 371.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 完美消化 雞肉、大麥及全燕麥特調食譜', N'維持腸道健康、營養不良、維持精實肌肉、想要維持器官健康', N'成貓', N'全適用', N'貓', 1, 0, 385.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用k/d Early Support 腎臟病早期護理(處方食品)', N'腎臟不好、想維持理想體重、食慾不好、腸道不好', N'成貓', N'全適用', N'貓', 1, 0, 408.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 7歲以上 高齡活力 雞肉特調食譜', N'沒活力、保持消化健康、想維持毛髮亮麗', N'老貓', N'全適用', N'貓', 1, 0, 378.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓7歲以上 完美消化 雞肉、大麥及全燕麥特調食譜', N'維持腸道健康、營養不良、維持精實肌肉、想要維持器官健康', N'老貓', N'全適用', N'貓', 1, 0, 381.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用k/d 腎臟病護理 海魚(處方食品)', N'腎臟不好、食慾不好、腸胃不好、沒活力', N'成貓', N'全適用', N'貓', 1, 0, 408.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 c/d 全效(處方食品)', N'泌尿道不健康、有膀胱結石、膀胱問題', N'成貓', N'全適用', N'貓', 1, 0, 384.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用k/d+j/d 腎臟病護理+關節活動力(處方食品)', N'腎臟不好、食慾不好、腸胃不好、沒活力、關節不好', N'成貓', N'全適用', N'貓', 1, 0, 408.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 Metabolic體重管理(處方食品)', N'體重過胖、降低泌尿道結石', N'成貓', N'胖貓', N'貓', 1, 0, 339.8);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 r/d(處方食品)', N'維持精實肌肉、加強免疫系統、體重過胖', N'成貓', N'胖貓', N'貓', 1, 0, 295.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 y/d(處方食品)', N'甲狀腺功能亢進、皮膚不好、維持心臟，腎臟及膀胱健康、維持精實肌肉', N'成貓', N'全適用', N'貓', 1, 0, 400.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 z/d(處方食品)', N'食物敏感、腸胃不好、改善毛髮狀態、稀便、降低泌尿道結石', N'成貓', N'全適用', N'貓', 1, 0, 384.7);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 w/d(處方食品)', N'體重過胖、血糖不正常、穩定糞便狀態、泌尿道不健康、想維持精實肌肉', N'成貓', N'胖貓', N'貓', 1, 0, 322.5);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'貓用 m/d(處方食品)', N'體重過胖、血糖不正常、想維持免疫系統健康、降低泌尿道結石', N'成貓', N'胖貓', N'貓', 1, 0, 398.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 敏感胃腸與皮膚 雞肉與米特調食譜', N'腸胃不好、皮膚不好、消化不好、想維持毛髮亮麗', N'成貓', N'全適用', N'貓', 1, 0, 410.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'幼貓 敏感胃腸與皮膚 鮭魚與糙米特調食譜', N'腸胃不好、皮膚不好、消化不好、想維持毛髮亮麗、幫助大腦發育', N'幼貓', N'全適用', N'貓', 1, 0, 415);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 毛球控制 低卡 雞肉特調食譜', N'體重過胖、維持心臟和眼睛健康、想維持毛髮亮麗、化毛不順利', N'成貓', N'胖貓', N'貓', 1, 0, 318);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 泌尿道毛球控制 雞肉與米特調食譜', N'泌尿道不健康、化毛不順利、想維護消化系統健康', N'成貓', N'全適用', N'貓', 1, 0, 368.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 毛球控制 雞肉特調食譜', N'維持心臟和眼睛健康、想維持毛髮亮麗、化毛不順利', N'成貓', N'全適用', N'貓', 1, 0, 365.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 7歲以上 毛球控制 雞肉特調食譜', N'維持心臟和眼睛健康、想維持毛髮亮麗、化毛不順利', N'老貓', N'全適用', N'貓', 1, 0, 371.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 完美體重 雞肉特調食譜', N'體重過胖、新陳代謝不好、想維持理想體重', N'成貓', N'全適用', N'貓', 1, 0, 341.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'室內成貓 7歲以上 雞肉特調食譜', N'沒活力、想維持毛髮亮麗、消化不好、維持心臟，腎臟及膀胱健康、保持消化健康、想維持理想體重', N'老貓', N'全適用', N'貓', 1, 0, 357.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 7歲以上', N'沒活力、、維持心臟，腎臟及膀胱健康、保持消化健康', N'老貓', N'全適用', N'貓', 1, 0, 392.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 雞肉特調食譜', N'維持精實肌肉、想維持毛髮亮麗、支持消化，免疫和器官健康', N'成貓', N'全適用', N'貓', 1, 0, 387.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'室內成貓 雞肉特調食譜', N'維持精實肌肉、想維持毛髮亮麗、支持消化，免疫和器官健康', N'成貓', N'全適用', N'貓', 1, 0, 349.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 11歲以上 雞肉特調食譜', N'維持心臟和眼睛健康、維持精實肌肉、想要維持器官健康', N'老貓', N'全適用', N'貓', 1, 0, 404.4);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 鮭魚與糙米特調食譜', N'維持精實肌肉、想維持毛髮亮麗、想要維持器官健康', N'成貓', N'全適用', N'貓', 1, 0, 394.2);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'幼貓 雞肉特調食譜', N'幫助骨骼生長、支持腦部發育、維持腸道健康、維護免疫力、促進肌肉精實、挑食', N'幼貓', N'全適用', N'貓', 1, 0, 407.6);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'希爾思', N'成貓 低卡 雞肉特調食譜', N'消化不好、想維持毛髮亮麗、維持精實肌肉、維持理想體重', N'成貓', N'胖貓', N'貓', 1, 0, 317.1);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'星益生趣', N'凍乾塗層無穀犬糧 生鮮白魚配方', N'腸胃不好、容易過敏、挑食、保護關節、想維持毛髮亮麗、牙齒不好', N'全年齡', N'全適用', N'狗', 0, 1, 367.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'星益生趣', N'凍乾塗層無穀貓糧 生鮮鮭魚配方', N'消化不好、想維持毛髮亮麗、腸胃不好、容易過敏、挑食', N'全年齡', N'全適用', N'貓', 0, 1, 374.3);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'星益生趣', N'凍乾無穀貓糧 三種魚配方', N'消化不好、想維持毛髮亮麗、腸胃不好、容易過敏、挑食', N'全年齡', N'全適用', N'貓', 0, 1, 372.9);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'奇境', N'無穀成貓糧 凍乾 尖吻鱸&鮪魚＋羊肺', N'腸胃不好、消化不好、維持視力', N'全年齡', N'全適用', N'貓', 0, 1, 360);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'奇境', N'無穀成貓糧 凍乾 鮭魚＋羊肺', N'腸胃不好、消化不好、維持視力、心血管健康、保護骨質', N'全年齡', N'全適用', N'貓', 0, 1, 360);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'奇境', N'無穀成貓糧 凍乾 野生袋鼠＋羊肺', N'腸胃不好、消化不好、幫助身體正常代謝、維持理想體重', N'全年齡', N'胖貓', N'貓', 0, 1, 360);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'奇境', N'無穀成貓糧 凍乾 澳洲牛肉+紐西蘭羊肺', N'腸胃不好、消化不好、心血管健康、維持視力、幫助肌肉發展', N'全年齡', N'全適用', N'貓', 0, 1, 360);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'野宴LIVINWILD', N'全齡貓草飼無穀配方 草飼羊&野牧山羊', N'腸胃不好、消化不好、泌尿道健康、補充營養', N'全年齡', N'全適用', N'貓', 1, 0, 344);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'野宴LIVINWILD', N'全齡貓-新鮮無穀配方 野生帝王鮭魚', N'腸胃不好、消化不好、泌尿道健康、維持免疫力、心血管健康', N'全年齡', N'全適用', N'貓', 1, 0, 351);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'野宴LIVINWILD', N'全齡犬-草飼無穀配方 草飼牛&牧野山羊', N'腸胃不好、消化不好、幫助肌肉發展', N'全年齡', N'全適用', N'狗', 1, 0, 351);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'貓倍麗', N'成貓海鮮拼盤泌尿保健', N'泌尿道健康', N'成貓', N'全適用', N'貓', 1, 1, 314);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'貓倍麗', N'成貓海洋魚高纖化毛', N'想維持毛髮亮麗、化毛不順利', N'成貓', N'全適用', N'貓', 1, 1, 338);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'極光', N'無穀全齡犬-羊肉(低脂)', N'腸胃不好、消化不好、營養不良', N'全年齡', N'全適用', N'狗', 1, 1, 330);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'', N'無穀全齡犬-雞肉&鴨肉', N'腸胃不好、消化不好、營養不良', N'全年齡', N'全適用', N'狗', 1, 1, 364);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'極光', N'無穀全齡犬-鮭魚&雪蟹', N'腸胃不好、消化不好、營養不良', N'全年齡', N'全適用', N'狗', 1, 1, 359);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'極光', N'全齡貓 無穀雞肉', N'腸胃不好、消化不好、營養不良、幫助肌肉發展', N'全年齡', N'全適用', N'貓', 1, 1, 355);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'極光', N'全齡貓 無穀鮭魚、鯡魚＆雪蟹', N'腸胃不好、消化不好、營養不良、幫助肌肉發展、加強免疫系統、維持骨骼健康', N'全年齡', N'全適用', N'貓', 1, 1, 350);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'極光', N'全齡貓 無穀雞肉&鮭魚', N'腸胃不好、消化不好、營養不良、維持精實肌肉、維持體態', N'全年齡', N'全適用', N'貓', 1, 1, 340);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'愛慕思', N'健康優活 成貓營養配方 鮪魚鮭魚', N'腸胃不好、消化不好、加強免疫系統、想維持毛髮亮麗', N'成貓', N'全適用', N'貓', 1, 1, 374);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'愛慕思', N'健康優活 室內貓體重及化毛營養配方', N'想維持毛髮亮麗、化毛不順利、維持體態、體重管理', N'成貓', N'室內貓', N'貓', 1, 1, 336);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'愛慕思', N'健康優活 幼貓母貓營養配方', N'腸胃不好、消化不好、加強免疫系統、視力發展', N'幼貓', N'懷孕貓 ', N'貓', 1, 1, 401);
INSERT INTO Food (Brand, Flavor, UseFor, AgeGroup, BodyType, PetType, AAFCO, ThirdPartyTest, Calories) VALUES (N'愛慕思', N'健康優活 幼犬母犬營養配方', N'腸胃不好、消化不好、加強免疫系統、認知能力發展', N'幼犬', N'懷孕犬', N'狗', 1, 1, 377);